### ISSUE TITLE
Build would not run - gevent imports - gevent.__hub_local.py - pyinstaller

### ISSUE THREAD

**Issue by jonbluhm** [Andrew-Shay/Neuron#14]
Hi - 
I recently cloned this repo and attempted to build as-is as I have a Flask app that I'd like to operate as a standalone app. Here are the issues I ran into.

1. Could not run `__main__.py` due to import errors
2. Once built, the *.exe would report import errors relating to gevent. (could not import gevent.__hub_local.py, gevent.__hub_primitives, etc)
3. cefpython would report errors that some data files could not be found. 

Here are the fixes

1. Changed `from gevent.wsgi import WSGIServer` to `from gevent.pywsgi import WSGIServer`
2. Recent versions of gevent cause problems with pyinstaller. I specified the version 1.2.2 in requirements and this eliminated this problem. I'm sure there is another way to use > 1.2.2 but I do not understand how to implement compiled modules with pyinstaller.
3. This is something with trying to find files with frozen installs. I changed the following section in `def main():` in `__main__.py`:
```
def main():
    check_versions()
    sys.excepthook = cef.ExceptHook  # To shutdown all CEF processes on error
    settings = {}
    if getattr(sys, 'frozen', False):
        settings = {
            'resources_dir_path': sys._MEIPASS,
            'locales_dir_path': sys._MEIPASS + os.sep + 'locales',
            'browser_subprocess_path': sys._MEIPASS + os.sep + 'subprocess.exe',
        }
```
Once I applied this fixes, I was able to build and run the exe file without issue. I was also able to edit the `build.spec` file to build into a single file.
I only use git for personal use as I'm completely an amateur so I'm not sure how to issue a pull request - if that's the correct thing to do. 

This repo helped me accomplish what I needed - thanks!

**Comment by Andrew-Shay** [comment]
Hey @jonbluhm I'm glad this project helped!  
v2.0.1 should fix the import errors 1 and 2 you had.  
Let me know if no. 3 is still an issue for you. I do not have that issue.
