### ISSUE TITLE
Upgrade to Python 3 and latest CEFPython

### ISSUE THREAD

**Issue by Andrew-Shay** [Andrew-Shay/Neuron#4]
- Upgrade to Python 3 and latest CEFPython

**Comment by coreilabs** [comment]
how I can help?

**Comment by Andrew-Shay** [comment]
@coreilabs This is actually complete, I just haven't pushed it yet since there are other new things included that aren't finished.

**Comment by Andrew-Shay** [comment]
Released in v2.0.0
